# 🧪 Pandas Wrangle Lab: Clean & Explore a Real Dataset

## 🔹 LEARNING GOALS:
- Practice loading, cleaning, and exploring real-world data
- Apply column creation, renaming, sorting, and filtering
- Use `.info()`, `.describe()`, and `.query()` fluently

### 📥 1. Load the Dataset

In [2]:
import pandas as pd
df = pd.read_csv("../../data/students.csv")
df.head()

  first_name last_name  math_score  science_score
0   Danielle      Wood         100             95
1      Angel     Clark          67             78
2     Joshua     Adams          61            100
3    Jeffrey    Zuniga          77             99
4       Jill      Wong          75             83

### 🔎 2. Inspect and Audit the Data

In [3]:
# Basic overview
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   first_name     50 non-null     str
 1   last_name      50 non-null     str
 2   math_score     50 non-null     int64
 3   science_score  50 non-null     int64
dtypes: int64(2), str(2)
memory usage: 1.7 KB

In [4]:
# Summary stats
df.describe()

       math_score  science_score
count    50.00000      50.000000
mean     77.56000      80.240000
std      12.17753      11.659384
min      60.00000      62.000000
25%      66.25000      73.000000
50%      75.50000      78.000000
75%      87.00000      89.000000
max     100.00000     100.000000

### 🧼 3. Clean Missing or Invalid Data

In [5]:
# Check for missing values
df.isnull().sum()

first_name       0
last_name        0
math_score       0
science_score    0
dtype: int64

In [6]:
# Drop rows with missing names
df.dropna(subset=["first_name", "last_name"], inplace=True)

# Fill any missing scores with column average
df["math_score"].fillna(df["math_score"].mean(), inplace=True)
df["science_score"].fillna(df["science_score"].mean(), inplace=True)

/var/folders/r8/59x4p3p13bv8n2f9q8mgm3s40000gn/T/ipykernel_26217/210016614.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["math_score"].fillna(df["math_score"].mean(), inplace=True)
/var/folders/r8/59x4p3p13bv8n2f9q8mgm3s40000gn/T/ipykernel_26217/210016614.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["science_score"].fillna(df["science_score"].mean(), inplace=True)

0      95
1      78
2     100
3      99
4      83
5      96
6      72
7      64
8      62
9      74
10     78
11     65
12     74
13     66
14     84
15     77
16     89
17    100
18     83
19     70
20     83
21     82
22     73
23     77
24     64
25     98
26    100
27     70
28     94
29     75
30     70
31     89
32     84
33     77
34    100
35     95
36     74
37     80
38     63
39     74
40     62
41     80
42     85
43     77
44     64
45     73
46     96
47     80
48     73
49     91
Name: science_score, dtype: int64

### 🧠 4. Feature Engineering (New Columns)

In [7]:
# Add average and grade
df["average_score"] = (df["math_score"] + df["science_score"]) / 2

def grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    elif score >= 70:
        return "C"
    else:
        return "D"

df["grade"] = df["average_score"].apply(grade)
df.head()

  first_name last_name  math_score  science_score  average_score grade
0   Danielle      Wood         100             95           97.5     A
1      Angel     Clark          67             78           72.5     C
2     Joshua     Adams          61            100           80.5     B
3    Jeffrey    Zuniga          77             99           88.0     B
4       Jill      Wong          75             83           79.0     C

### 🔽 5. Sorting and Filtering

In [8]:
# Top performers
df[df["average_score"] > 90].sort_values(by="average_score", ascending=False).head()

     first_name last_name  math_score  science_score  average_score grade
26  Christopher     Rocha          97            100           98.5     A
0      Danielle      Wood         100             95           97.5     A
17      Bridget   Johnson          92            100           96.0     A
46        Craig   Ferrell          94             96           95.0     A
25      Matthew    Foster          88             98           93.0     A

### 📊 6. Group and Describe by Grade

In [9]:
# How many of each grade?
df["grade"].value_counts()

grade
C    22
B    14
A     7
D     7
Name: count, dtype: int64

In [10]:
# Average scores per grade group
df.groupby("grade")[["math_score", "science_score", "average_score"]].mean()

       math_score  science_score  average_score
grade
A       95.285714      93.857143      94.571429
B       81.500000      86.857143      84.178571
C       73.590909      75.590909      74.590909
D       64.428571      68.000000      66.214286

### 💾 7. Save the Cleaned Dataset

In [11]:
df.to_csv("student_scores_cleaned.csv", index=False)

### 🧠 Challenge Task

> Your turn! Filter out students who got a D, sort by last name, and export to a new file:
- Only include columns: `first_name`, `last_name`, `grade`
- Save it as `"d_students.csv"`

In [12]:
d_students = df[df["grade"] == "D"]
d_students = d_students[["first_name", "last_name", "grade"]]
d_students = d_students.sort_values(by="last_name")
d_students.to_csv("d_students.csv", index=False)
print(d_students)

     first_name last_name grade
19         Adam     Adams     D
44  Christopher     Brown     D
13        James     Cohen     D
7   Christopher    Daniel     D
9       Anthony      Gray     D
12      Anthony   Hawkins     D
24        Susan      Rios     D

### 📝 Summary

This lab gave you hands-on experience with:
- Cleaning nulls and type mismatches
- Creating new columns
- Filtering and sorting real data
- Grouping and summarizing by categorical features

Your data wrangling toolbox is now ready for real-world messiness. 🧹🛠️