# 🧼 Cleaning Dirty Data (Missing Values & Type Fixes)

## 🔹 LEARNING GOALS:
- Detect and count missing values (`NaN`)
- Fill or drop missing data
- Convert column data types safely
- Understand the difference between `NaN`, `None`, `""`, and type mismatches

### 🧪 1. Load a Messy Dataset

In [1]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", None],
    "Age": ["25", "thirty", 35, np.nan, "40"],
    "Signup Date": ["2022-01-01", "not a date", "2022/03/01", None, "April 5, 2022"],
    "Score": [95.5, None, 88.0, 92.5, ""]
}

df = pd.DataFrame(data)
df

      Name     Age    Signup Date Score
0    Alice      25     2022-01-01  95.5
1      Bob  thirty     not a date  None
2  Charlie      35     2022/03/01  88.0
3    David     NaN            NaN  92.5
4      NaN      40  April 5, 2022

### 🧯 2. Detecting Missing or Broken Values

In [2]:
df.isnull()

    Name    Age  Signup Date  Score
0  False  False        False  False
1  False  False        False   True
2  False  False        False  False
3  False   True         True  False
4   True  False        False  False

In [3]:
df.isnull().sum()

Name           1
Age            1
Signup Date    1
Score          1
dtype: int64

In [4]:
df[df.isnull().any(axis=1)]

    Name     Age    Signup Date Score
1    Bob  thirty     not a date  None
3  David     NaN            NaN  92.5
4    NaN      40  April 5, 2022

### 🧹 3. Cleaning Strategy Options

In [5]:
df.fillna({
    "Name": "Unknown",
    "Age": -1,
    "Signup Date": "1970-01-01",
    "Score": 0.0
})

      Name     Age    Signup Date Score
0    Alice      25     2022-01-01  95.5
1      Bob  thirty     not a date   0.0
2  Charlie      35     2022/03/01  88.0
3    David      -1     1970-01-01  92.5
4  Unknown      40  April 5, 2022

In [6]:
df.dropna()

      Name Age Signup Date Score
0    Alice  25  2022-01-01  95.5
2  Charlie  35  2022/03/01  88.0

### 🧬 4. Data Type Fixes

In [7]:
df.dtypes

Name              str
Age            object
Signup Date       str
Score          object
dtype: object

In [8]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Score"] = pd.to_numeric(df["Score"], errors="coerce")
df["Signup Date"] = pd.to_datetime(df["Signup Date"], errors="coerce")
df.dtypes

Name                      str
Age                   float64
Signup Date    datetime64[us]
Score                 float64
dtype: object

### 🩹 5. Impute (Fill In) Fixed Missing Values

In [9]:
df["Age"].fillna(df["Age"].median(), inplace=True)
df["Score"].fillna(df["Score"].mean(), inplace=True)

/var/folders/r8/59x4p3p13bv8n2f9q8mgm3s40000gn/T/ipykernel_16948/1713118361.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Age"].fillna(df["Age"].median(), inplace=True)
/var/folders/r8/59x4p3p13bv8n2f9q8mgm3s40000gn/T/ipykernel_16948/1713118361.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Score"].fillna(df["Score"].mean(), inplace=True)

0    95.5
1    92.0
2    88.0
3    92.5
4    92.0
Name: Score, dtype: float64

In [10]:
df["Signup Date"].fillna(df["Signup Date"].min(), inplace=True)

/var/folders/r8/59x4p3p13bv8n2f9q8mgm3s40000gn/T/ipykernel_16948/3000949103.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Signup Date"].fillna(df["Signup Date"].min(), inplace=True)

0   2022-01-01
1   2022-01-01
2   2022-01-01
3   2022-01-01
4   2022-01-01
Name: Signup Date, dtype: datetime64[us]

In [11]:
df["Name"].fillna("Unknown", inplace=True)

/var/folders/r8/59x4p3p13bv8n2f9q8mgm3s40000gn/T/ipykernel_16948/626038248.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Name"].fillna("Unknown", inplace=True)

0      Alice
1        Bob
2    Charlie
3      David
4    Unknown
Name: Name, dtype: str

### 🤓 6. Cleaned Data Review

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         4 non-null      str
 1   Age          3 non-null      float64
 2   Signup Date  1 non-null      datetime64[us]
 3   Score        3 non-null      float64
dtypes: datetime64[us](1), float64(2), str(1)
memory usage: 292.0 bytes

In [13]:
df.describe(include="all")

         Name        Age          Signup Date      Score
count       4   3.000000                    1   3.000000
unique      4        NaN                  NaN        NaN
top     Alice        NaN                  NaN        NaN
freq        1        NaN                  NaN        NaN
mean      NaN  33.333333  2022-01-01 00:00:00  92.000000
min       NaN  25.000000  2022-01-01 00:00:00  88.000000
25%       NaN  30.000000  2022-01-01 00:00:00  90.250000
50%       NaN  35.000000  2022-01-01 00:00:00  92.500000
75%       NaN  37.500000  2022-01-01 00:00:00  94.000000
max       NaN  40.000000  2022-01-01 00:00:00  95.500000
std       NaN   7.637626                  NaN   3.774917

### 🧪 Try It Yourself

Modify the `data` dictionary at the top of this notebook. Add:
- A new column with some `None` and `""` values
- At least one row with all columns filled incorrectly
Then re-run the notebook and fix it step-by-step.

In [14]:
data = {
    "Name": ["Alice", "Bob", None, "David", ""],
    "Age": ["25", "thirty", None, "40", ""],
    "Signup Date": ["2022-01-01", "bad date", None, "2022/03/01", ""],
    "Score": [95.5, None, "eighty", 92.5, ""],
    "City": ["NY", None, "", "LA", "Chicago"]
}

df = pd.DataFrame(data)
df

    Name     Age Signup Date   Score     City
0  Alice      25  2022-01-01    95.5       NY
1    Bob  thirty    bad date    None      NaN
2    NaN     NaN         NaN  eighty
3  David      40  2022/03/01    92.5       LA
4                                     Chicago

### 🧠 Mini-Challenge

> 🗂 Load `"data/survey.csv"` and:
- Identify which columns have missing values
- Use `.isnull().sum()` to get a null report
- Use a mix of `.fillna()`, `.dropna()`, and `pd.to_numeric()` or `pd.to_datetime()` to clean it
- Print a summary with `.info()` and `.describe()`

In [16]:
survey = {
    "Name": ["Aakash", "John", None, "Mike", ""],
    "Age": ["25", "bad", None, "40", ""],
    "Score": [95, None, "eighty", 88, ""]
}

df = pd.DataFrame(survey)

df.isnull().sum()

df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Score"] = pd.to_numeric(df["Score"], errors="coerce")

df["Age"].fillna(df["Age"].median(), inplace=True)
df["Score"].fillna(df["Score"].mean(), inplace=True)
df["Name"].replace("", None, inplace=True)
df.dropna(inplace=True)

df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      float64
 2   Score   2 non-null      float64
dtypes: float64(2), str(1)
memory usage: 180.0 bytes

/var/folders/r8/59x4p3p13bv8n2f9q8mgm3s40000gn/T/ipykernel_16948/3873940007.py:14: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Age"].fillna(df["Age"].median(), inplace=True)
/var/folders/r8/59x4p3p13bv8n2f9q8mgm3s40000gn/T/ipykernel_16948/3873940007.py:15: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Score"].fillna(df["Score"].mean(), inplace=True)
/var/folders/r8/59x4p3p13bv8n2f9q8mgm3s40000gn/T/ipykernel_16948/3873940007.py:16: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Name"].replace("", None, inplace=True)

             Age      Score
count   2.000000   2.000000
mean   32.500000  91.500000
std    10.606602   4.949747
min    25.000000  88.000000
25%    28.750000  89.750000
50%    32.500000  91.500000
75%    36.250000  93.250000
max    40.000000  95.000000

### 📝 Summary

| Concept        | Tool/Function                      |
|----------------|------------------------------------|
| Detect nulls   | `df.isnull()`, `df.isnull().sum()` |
| Drop rows      | `df.dropna()`                      |
| Fill values    | `df.fillna()`                      |
| Convert types  | `pd.to_numeric()`, `pd.to_datetime()` |
| Replace values | `df.replace()`                     |