# 🧮 Sorting & Filtering in Pandas

## 🔹 LEARNING GOALS:
- Sort rows using `.sort_values()`
- Filter data using conditional logic
- Chain multiple filters together
- Use `.query()` for readable filtering

### 📥 1. Load the Dataset

In [7]:
import pandas as pd

df = pd.read_csv("../../data/students.csv")
df.head()

  first_name last_name  math_score  science_score
0   Danielle      Wood         100             95
1      Angel     Clark          67             78
2     Joshua     Adams          61            100
3    Jeffrey    Zuniga          77             99
4       Jill      Wong          75             83

### 🔢 2. Sorting Data

In [8]:
# Sort by math_score
df.sort_values(by="math_score")

     first_name  last_name  math_score  science_score
28      Melanie      Baker          60             94
2        Joshua      Adams          61            100
13        James      Cohen          61             66
19         Adam      Adams          61             70
44  Christopher      Brown          62             64
12      Anthony    Hawkins          62             74
49      Michael   Valencia          65             91
14        Debra    Cameron          65             84
37    Christine      Hicks          65             80
9       Anthony       Gray          65             74
36        Maria     Bright          66             74
39      Barbara   Williams          66             74
7   Christopher     Daniel          66             64
47       Joshua       Rice          67             80
1         Angel      Clark          67             78
6      Patricia    Jackson          68             72
33       Teresa      Hurst          69             77
29    Cassandra     Wright          70             75
21        Helen       Hahn          72             82
34     Nicholas       Ross          73            100
15          Amy    Parsons          73             77
24        Susan       Rios          74             64
5         Erica      Lynch          74             96
16      Jeffrey      Perez          74             89
4          Jill       Wong          75             83
43        Keith  Henderson          76             77
3       Jeffrey     Zuniga          77             99
27        Colin      Ellis          77             70
32       Amanda   Richards          77             84
35       Andrea   Robinson          81             95
31      Jessica      Baker          81             89
40        Janet  Rodriguez          82             62
41      Brandon     Burton          82             80
48      Cynthia     Maddox          84             73
38     Michelle      Davis          84             63
23         Eric    Edwards          86             77
11      William     Bowman          87             65
30      Lindsay    Hoffman          87             70
25      Matthew     Foster          88             98
45        Jesse      James          89             73
17      Bridget    Johnson          92            100
46        Craig    Ferrell          94             96
22      Matthew     Walter          94             73
8        Robert     Martin          94             62
20        Linda      Clark          95             83
10      Jeffery       Mayo          97             78
26  Christopher      Rocha          97            100
18         Lisa    Stewart          98             83
42       Jeremy     Conner          98             85
0      Danielle       Wood         100             95

In [9]:
# Sort by science_score descending
df.sort_values(by="science_score", ascending=False)

     first_name  last_name  math_score  science_score
17      Bridget    Johnson          92            100
2        Joshua      Adams          61            100
34     Nicholas       Ross          73            100
26  Christopher      Rocha          97            100
3       Jeffrey     Zuniga          77             99
25      Matthew     Foster          88             98
46        Craig    Ferrell          94             96
5         Erica      Lynch          74             96
35       Andrea   Robinson          81             95
0      Danielle       Wood         100             95
28      Melanie      Baker          60             94
49      Michael   Valencia          65             91
16      Jeffrey      Perez          74             89
31      Jessica      Baker          81             89
42       Jeremy     Conner          98             85
14        Debra    Cameron          65             84
32       Amanda   Richards          77             84
4          Jill       Wong          75             83
18         Lisa    Stewart          98             83
20        Linda      Clark          95             83
21        Helen       Hahn          72             82
47       Joshua       Rice          67             80
41      Brandon     Burton          82             80
37    Christine      Hicks          65             80
1         Angel      Clark          67             78
10      Jeffery       Mayo          97             78
43        Keith  Henderson          76             77
23         Eric    Edwards          86             77
33       Teresa      Hurst          69             77
15          Amy    Parsons          73             77
29    Cassandra     Wright          70             75
36        Maria     Bright          66             74
39      Barbara   Williams          66             74
12      Anthony    Hawkins          62             74
9       Anthony       Gray          65             74
45        Jesse      James          89             73
22      Matthew     Walter          94             73
48      Cynthia     Maddox          84             73
6      Patricia    Jackson          68             72
30      Lindsay    Hoffman          87             70
27        Colin      Ellis          77             70
19         Adam      Adams          61             70
13        James      Cohen          61             66
11      William     Bowman          87             65
7   Christopher     Daniel          66             64
44  Christopher      Brown          62             64
24        Susan       Rios          74             64
38     Michelle      Davis          84             63
40        Janet  Rodriguez          82             62
8        Robert     Martin          94             62

In [10]:
# Sort by multiple columns
df.sort_values(by=["science_score", "math_score"], ascending=[False, True])

     first_name  last_name  math_score  science_score
2        Joshua      Adams          61            100
34     Nicholas       Ross          73            100
17      Bridget    Johnson          92            100
26  Christopher      Rocha          97            100
3       Jeffrey     Zuniga          77             99
25      Matthew     Foster          88             98
5         Erica      Lynch          74             96
46        Craig    Ferrell          94             96
35       Andrea   Robinson          81             95
0      Danielle       Wood         100             95
28      Melanie      Baker          60             94
49      Michael   Valencia          65             91
16      Jeffrey      Perez          74             89
31      Jessica      Baker          81             89
42       Jeremy     Conner          98             85
14        Debra    Cameron          65             84
32       Amanda   Richards          77             84
4          Jill       Wong          75             83
20        Linda      Clark          95             83
18         Lisa    Stewart          98             83
21        Helen       Hahn          72             82
37    Christine      Hicks          65             80
47       Joshua       Rice          67             80
41      Brandon     Burton          82             80
1         Angel      Clark          67             78
10      Jeffery       Mayo          97             78
33       Teresa      Hurst          69             77
15          Amy    Parsons          73             77
43        Keith  Henderson          76             77
23         Eric    Edwards          86             77
29    Cassandra     Wright          70             75
12      Anthony    Hawkins          62             74
9       Anthony       Gray          65             74
36        Maria     Bright          66             74
39      Barbara   Williams          66             74
48      Cynthia     Maddox          84             73
45        Jesse      James          89             73
22      Matthew     Walter          94             73
6      Patricia    Jackson          68             72
19         Adam      Adams          61             70
27        Colin      Ellis          77             70
30      Lindsay    Hoffman          87             70
13        James      Cohen          61             66
11      William     Bowman          87             65
44  Christopher      Brown          62             64
7   Christopher     Daniel          66             64
24        Susan       Rios          74             64
38     Michelle      Davis          84             63
40        Janet  Rodriguez          82             62
8        Robert     Martin          94             62

### 🧪 3. Filtering with Conditions

In [11]:
# Who scored at least 90 in math?
df[df["math_score"] >= 90]

     first_name last_name  math_score  science_score
0      Danielle      Wood         100             95
8        Robert    Martin          94             62
10      Jeffery      Mayo          97             78
17      Bridget   Johnson          92            100
18         Lisa   Stewart          98             83
20        Linda     Clark          95             83
22      Matthew    Walter          94             73
26  Christopher     Rocha          97            100
42       Jeremy    Conner          98             85
46        Craig   Ferrell          94             96

In [12]:
# Who scored less than 70 in either subject?
df[(df["math_score"] < 70) | (df["science_score"] < 70)]

     first_name  last_name  math_score  science_score
1         Angel      Clark          67             78
2        Joshua      Adams          61            100
6      Patricia    Jackson          68             72
7   Christopher     Daniel          66             64
8        Robert     Martin          94             62
9       Anthony       Gray          65             74
11      William     Bowman          87             65
12      Anthony    Hawkins          62             74
13        James      Cohen          61             66
14        Debra    Cameron          65             84
19         Adam      Adams          61             70
24        Susan       Rios          74             64
28      Melanie      Baker          60             94
33       Teresa      Hurst          69             77
36        Maria     Bright          66             74
37    Christine      Hicks          65             80
38     Michelle      Davis          84             63
39      Barbara   Williams          66             74
40        Janet  Rodriguez          82             62
44  Christopher      Brown          62             64
47       Joshua       Rice          67             80
49      Michael   Valencia          65             91

### 🔗 4. Combining Filters

In [13]:
# Students with B+ or higher in both
df[(df["math_score"] >= 87) & (df["science_score"] >= 87)]

     first_name last_name  math_score  science_score
0      Danielle      Wood         100             95
17      Bridget   Johnson          92            100
25      Matthew    Foster          88             98
26  Christopher     Rocha          97            100
46        Craig   Ferrell          94             96

### 🧾 5. Using `.query()` for Readability

In [14]:
# Same query using .query()
df.query("math_score >= 87 and science_score >= 87")

     first_name last_name  math_score  science_score
0      Danielle      Wood         100             95
17      Bridget   Johnson          92            100
25      Matthew    Foster          88             98
26  Christopher     Rocha          97            100
46        Craig   Ferrell          94             96

### 🧪 Try It Yourself

- Sort the dataset by first name alphabetically
- Find students with the same math and science score
- Use `.query()` to find students who scored over 95 in *either* subject

In [15]:
df.sort_values(by="first_name")

df[df["math_score"] == df["science_score"]]

df.query("math_score > 95 or science_score > 95")

     first_name last_name  math_score  science_score
0      Danielle      Wood         100             95
2        Joshua     Adams          61            100
3       Jeffrey    Zuniga          77             99
5         Erica     Lynch          74             96
10      Jeffery      Mayo          97             78
17      Bridget   Johnson          92            100
18         Lisa   Stewart          98             83
25      Matthew    Foster          88             98
26  Christopher     Rocha          97            100
34     Nicholas      Ross          73            100
42       Jeremy    Conner          98             85
46        Craig   Ferrell          94             96

### 🧠 Mini-Challenge

> Load `"data/survey.csv"` and:
- Sort by the most recent signup date
- Filter out anyone who didn't complete the survey (nulls or "N/A")
- Use `.query()` to select rows with a specific condition of your choice

In [16]:
survey = pd.read_csv("../../data/survey.csv")
print(survey.head())

survey_clean = survey.dropna()
print(survey_clean.head())

  student_id  age  gender             major   gpa study_hours_per_week  \
0     S10000  NaN    Male  Computer Science   NaN                  NaN
1     S10001  NaN    Male           CompSci  3.75                   -3
2     S10002   23    Male      Data Science   NaN                   20
3     S10003  NaN  Female           History   5.1                  NaN
4     S10004  NaN  Female           CompSci   NaN                    0

  satisfaction_1_5 survey_date dorm_resident expected_grad_year  \
0                2  2025-13-40           Yes               2027
1              NaN         NaN           Yes                NaN
2                5  2025-13-40           NaN               2027
3              NaN         NaN            No                NaN
4                5  2025-13-40           Yes               2029

        income_range commute_minutes clubs_member attendance_rate  \
0             >$100k              54         TRUE            105%
1                NaN             NaN            1             NaN
2         $75k-$100k             NaN          NaN             64%
3          $25k-$50k              15           No            105%
4  Prefer not to say              41           No             NaN

  favorite_language          comments
0        JavaScript  Love the course.
1              Rust    Lectures are 🔥
2        JavaScript               NaN
3              Rust               NaN
4            Python               NaN
Empty DataFrame
Columns: [student_id, age, gender, major, gpa, study_hours_per_week, satisfaction_1_5, survey_date, dorm_resident, expected_grad_year, income_range, commute_minutes, clubs_member, attendance_rate, favorite_language, comments]
Index: []

### 📝 Summary

| Task              | Code Example                                 |
|-------------------|-----------------------------------------------|
| Sort by column     | `df.sort_values(by="col")`                  |
| Filter condition   | `df[df["col"] > value]`                     |
| Combine filters    | `df[(cond1) & (cond2)]`                     |
| Query method       | `df.query("col > value and col2 < value")`  |