
# 🧼 Data Cleaning Lab: Survey Edition

Welcome to the data cleaning battlefield! This notebook contains a messy `survey_dirty.csv` file full of inconsistencies, missing values, and formatting nightmares. Your task is to clean it up using pandas and your data wrangling skills.

---

📁 **File to use**: `survey_dirty.csv`  
📊 **Goal**: Practice common data cleaning tasks on a realistic (but slightly cursed) dataset.


## ✅ Cleaning Tasks

Complete the following tasks step-by-step. Use new cells for each task and document your process.

### 1. Load and inspect the data
- Load the CSV file into a DataFrame
- Display the first few rows and basic info (`df.info()`)

### 2. Clean up string fields
- Strip whitespace from `name`, `email`, and other string columns
- Identify blank strings and convert them to NaN if needed

### 3. Handle missing values
- Identify columns with missing data
- Decide how to handle them: drop, fill, or flag (justify your choices)

### 4. Standardize categorical data
- Convert `gender` values to consistent categories (`Male`, `Female`, `Other`)
- Normalize `exercise_freq` to a standard set of categories

### 5. Fix data types
- Convert `age`, `height_cm`, `weight_kg`, and `satisfaction` to numeric
- Extract numbers from strings (e.g., "175cm" → 175)
- Convert `submitted_at` to datetime

### 6. Validate and clean emails
- Use regex or string methods to filter out invalid email addresses

### 7. Convert consent to Boolean
- Standardize `consent_given` to True/False values

### 8. Check for duplicates
- Identify any duplicated rows or IDs
- Drop or resolve as needed

### 9. Save your cleaned data
- Save the cleaned DataFrame to a new file called `survey_clean.csv`

In [3]:
import pandas as pd

df = pd.read_csv("../../data/survey.csv")
df.head()

,student_id,age,gender,major,gpa,study_hours_per_week,satisfaction_1_5,survey_date,dorm_resident,expected_grad_year,income_range,commute_minutes,clubs_member,attendance_rate,favorite_language,comments
0,S10000,NaN,Male,Computer Science,NaN,NaN,2,2025-13-40,Yes,2027,>$100k,54,TRUE,105%,JavaScript,Love the course.
1,S10001,NaN,Male,CompSci,3.75,-3,NaN,NaN,Yes,NaN,NaN,NaN,1,NaN,Rust,Lectures are 🔥
2,S10002,23,Male,Data Science,NaN,20,5,2025-13-40,NaN,2027,$75k-$100k,NaN,NaN,64%,JavaScript,NaN
3,S10003,NaN,Female,History,5.1,NaN,NaN,NaN,No,NaN,$25k-$50k,15,No,105%,Rust,NaN
4,S10004,NaN,Female,CompSci,NaN,0,5,2025-13-40,Yes,2029,Prefer not to say,41,No,NaN,Python,NaN

In [4]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            120 non-null    str
 1   age                   87 non-null     str
 2   gender                97 non-null     str
 3   major                 110 non-null    str
 4   gpa                   76 non-null     str
 5   study_hours_per_week  78 non-null     str
 6   satisfaction_1_5      74 non-null     str
 7   survey_date           88 non-null     str
 8   dorm_resident         87 non-null     str
 9   expected_grad_year    87 non-null     str
 10  income_range          99 non-null     str
 11  commute_minutes       67 non-null     str
 12  clubs_member          95 non-null     str
 13  attendance_rate       41 non-null     str
 14  favorite_language     101 non-null    str
 15  comments              68 non-null     str
dtypes: str(16)
memory usage: 15.1 KB

,student_id,age,gender,major,gpa,study_hours_per_week,satisfaction_1_5,survey_date,dorm_resident,expected_grad_year,income_range,commute_minutes,clubs_member,attendance_rate,favorite_language,comments
count,120,87,97,110,76,78,74,88,87,87,99,67,95,41,101,68
unique,120,9,4,9,14,14,6,60,4,6,6,16,6,14,7,4
top,S10000,19,Male,CS,3.75,-3,2,2025-13-40,Yes,2027,>$100k,-5,1,105%,Rust,Love the course.
freq,1,16,28,20,22,15,18,27,29,19,22,17,25,25,18,22

In [5]:
df["gender"] = df["gender"].str.strip()
df["major"] = df["major"].str.strip()
df["comments"] = df["comments"].str.strip()

df = df.replace("N/A", pd.NA)
df = df.replace("", pd.NA)

df.head()

,student_id,age,gender,major,gpa,study_hours_per_week,satisfaction_1_5,survey_date,dorm_resident,expected_grad_year,income_range,commute_minutes,clubs_member,attendance_rate,favorite_language,comments
0,S10000,NaN,Male,Computer Science,NaN,NaN,2,2025-13-40,Yes,2027,>$100k,54,TRUE,105%,JavaScript,Love the course.
1,S10001,NaN,Male,CompSci,3.75,-3,NaN,NaN,Yes,NaN,NaN,NaN,1,NaN,Rust,Lectures are 🔥
2,S10002,23,Male,Data Science,NaN,20,5,2025-13-40,NaN,2027,$75k-$100k,NaN,NaN,64%,JavaScript,NaN
3,S10003,NaN,Female,History,5.1,NaN,NaN,NaN,No,NaN,$25k-$50k,15,No,105%,Rust,NaN
4,S10004,NaN,Female,CompSci,NaN,0,5,2025-13-40,Yes,2029,Prefer not to say,41,No,NaN,Python,NaN

In [6]:
print(df.isnull().sum())

df = df.dropna(subset=["student_id"])

student_id               0
age                     33
gender                  23
major                   10
gpa                     44
study_hours_per_week    42
satisfaction_1_5        46
survey_date             32
dorm_resident           33
expected_grad_year      33
income_range            21
commute_minutes         53
clubs_member            25
attendance_rate         79
favorite_language       19
comments                52
dtype: int64

In [7]:
df["major"] = df["major"].replace({
    "CS": "Computer Science",
    "CompSci": "Computer Science"
})

print(df["major"].value_counts())

major
Computer Science    37
Undeclared          15
History             14
Data Science        13
Business            12
Math                10
Biology              9
Name: count, dtype: int64

In [8]:
df.to_csv("survey_clean.csv", index=False)
print("Saved!")

Saved!